# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crear_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Crear_usuario(object):
    def setupUi(self, Crear_usuario):
        Crear_usuario.setObjectName("Crear_usuario")
        Crear_usuario.resize(358, 220)
        self.centralwidget = QtWidgets.QWidget(Crear_usuario)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 311, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_registrar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_registrar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_registrar.setObjectName("verticalLayout_registrar")
        self.frame_registrar = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_registrar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_registrar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_registrar.setObjectName("frame_registrar")
        self.registrar_label_lineEdit_cedula = QtWidgets.QLineEdit(self.frame_registrar)
        self.registrar_label_lineEdit_cedula.setGeometry(QtCore.QRect(130, 50, 111, 21))
        self.registrar_label_lineEdit_cedula.setObjectName("registrar_label_lineEdit_cedula")
        self.registrar_label_cedula = QtWidgets.QLabel(self.frame_registrar)
        self.registrar_label_cedula.setGeometry(QtCore.QRect(80, 50, 47, 13))
        self.registrar_label_cedula.setObjectName("registrar_label_cedula")
        self.registrar_label_nombre = QtWidgets.QLabel(self.frame_registrar)
        self.registrar_label_nombre.setGeometry(QtCore.QRect(80, 80, 47, 13))
        self.registrar_label_nombre.setObjectName("registrar_label_nombre")
        self.registrar_label_lineEdit_nombre = QtWidgets.QLineEdit(self.frame_registrar)
        self.registrar_label_lineEdit_nombre.setGeometry(QtCore.QRect(130, 80, 111, 21))
        self.registrar_label_lineEdit_nombre.setObjectName("registrar_label_lineEdit_nombre")
        self.registrar_label_titulo = QtWidgets.QLabel(self.frame_registrar)
        self.registrar_label_titulo.setGeometry(QtCore.QRect(20, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.registrar_label_titulo.setFont(font)
        self.registrar_label_titulo.setObjectName("registrar_label_titulo")
        self.registrar_pushButton_volver = QtWidgets.QPushButton(self.frame_registrar)
        self.registrar_pushButton_volver.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.registrar_pushButton_volver.setObjectName("registrar_pushButton_volver")
        self.registrar_crear = QtWidgets.QPushButton(self.frame_registrar)
        self.registrar_crear.setGeometry(QtCore.QRect(220, 110, 75, 23))
        self.registrar_crear.setObjectName("registrar_crear")
        self.verticalLayout_registrar.addWidget(self.frame_registrar)
        Crear_usuario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Crear_usuario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 21))
        self.menubar.setObjectName("menubar")
        Crear_usuario.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Crear_usuario)
        self.statusbar.setObjectName("statusbar")
        Crear_usuario.setStatusBar(self.statusbar)

        self.retranslateUi(Crear_usuario)
        QtCore.QMetaObject.connectSlotsByName(Crear_usuario)

    def retranslateUi(self, Crear_usuario):
        _translate = QtCore.QCoreApplication.translate
        Crear_usuario.setWindowTitle(_translate("Crear_usuario", "MainWindow"))
        self.registrar_label_cedula.setText(_translate("Crear_usuario", "Cédula"))
        self.registrar_label_nombre.setText(_translate("Crear_usuario", "Nombre"))
        self.registrar_label_titulo.setText(_translate("Crear_usuario", "Registrar usuario"))
        self.registrar_pushButton_volver.setText(_translate("Crear_usuario", "Volver"))
        self.registrar_crear.setText(_translate("Crear_usuario", "Crear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Crear_usuario = QtWidgets.QMainWindow()
    ui = Ui_Crear_usuario()
    ui.setupUi(Crear_usuario)
    Crear_usuario.show()
    sys.exit(app.exec_())
